---
name: first-network-org1 with fabric 1.4.x
version: 1.0.0

client:
  # The value must be the name of an org defined under "organizations"
  organization: Org1
  logging:
    level: info

# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  mychannel:
    peers:
      peer1-org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

#
# list of participating organizations in this network
#
organizations:
  Org1:
    mspid: Org1MSP
    cryptoPath: /Users/ymh/fkfabric/Org1/client/msp
    peers:
      - peer1-org1
    certificateAuthorities:
      - fabric-ca.stringon.com


peers:
  peer1-org1:
    url: grpcs://peer1-org1:7051
    grpcOptions:
      ssl-target-name-override: peer1-org1
      hostnameOverride: peer1-org1
    tlsCACerts:
      path: /Users/ymh/fkfabric/Org1/peer1/tlscacerts/tls-fabric-ca-stringon-com-7054.pem
#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  fabric-ca.stringon.com:
    url: https://fabric-ca.stringon.com:7054
    caName:
    tlsCACerts:
      path: /Users/ymh/fkfabric/tls-cert.pem
    registrar:
      enrollId: org1-admin
      enrollSecret: password
